/// Module for [StaticResource] class
module gio.static_resource;

public import gid.basictypes;
import gid.gid;
import gio.c.functions;
import gio.c.types;
import gio.resource;
import gio.types;

/**
    #GStaticResource is an opaque data structure and can only be accessed
    using the following functions.
*/
class StaticResource
{
  GStaticResource _cInstance;

  /** */
  this(void* ptr, Flag!"Take" take) nothrow
  {
    _cInstance = *cast(GStaticResource*)ptr;

    if (take)
      gFree(ptr);
  }

  /** */
  void* _cPtr() nothrow
  {
    return cast(void*)&_cInstance;
  }

  /**
      Finalized a GResource initialized by [gio.static_resource.StaticResource.init_].
      
      This is normally used by code generated by
      [glib-compile-resources][glib-compile-resources]
      and is not typically used by other code.
  */
  void fini() nothrow
  {
    g_static_resource_fini(cast(GStaticResource*)this._cPtr);
  }

  /**
      Gets the GResource that was registered by a call to [gio.static_resource.StaticResource.init_].
      
      This is normally used by code generated by
      [glib-compile-resources][glib-compile-resources]
      and is not typically used by other code.
      Returns: a #GResource
  */
  gio.resource.Resource getResource() nothrow
  {
    GResource* _cretval;
    _cretval = g_static_resource_get_resource(cast(GStaticResource*)this._cPtr);
    auto _retval = _cretval ? new gio.resource.Resource(cast(void*)_cretval, No.Take) : null;
    return _retval;
  }

  /**
      Initializes a GResource from static data using a
      GStaticResource.
      
      This is normally used by code generated by
      [glib-compile-resources][glib-compile-resources]
      and is not typically used by other code.
  */
  void init_() nothrow
  {
    g_static_resource_init(cast(GStaticResource*)this._cPtr);
  }
}
